---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangpengyong.
--- DateTime: 2022/11/2 22:48
---

print("-------------------------")
print("抛出异常：")
do
    function throwError()
        --- 不记录抛出异常的位置
        --error("error test", 0)
        --- 抛出异常的位置，即当前
        --error("error test", 1)
        --- 抛出异常的函数位置，即调用 throwError 的位置
        --error("error test", 2)
    end
    throwError()
end

print("-------------------------")
print("assert 抛出异常：")
do
    function showInfo()
        return "江澎涌", 29, 170
    end
    print(showInfo())
    print(assert(showInfo(), "error test"))

    --print(assert(nil, "error test"))

    function showInfoWithError()
        return false, "error test inner"
    end
    print(showInfoWithError())
    --print(assert(showInfoWithError()))
end

print("-------------------------")
print("pcall try-catch：")
do
    local ok1, msg = pcall(function()
        error("error via pcall catch")
    end)
    print(ok1, msg)

    local ok2, name, age = pcall(function(name, age)
        print("receive args: ", name, age)
        return name, age
    end, "Jiang pengyong", 29)
    print(ok2, name, age)

    --- error 可以传递不同的对象，pcall 会获取相对应的对象
    local ok3, error = pcall(function()
        error({ code = 100, msg = "error in a table" })
    end)
    print(ok3, error.code, error.msg)
end

print("-------------------------")
print("xpcall try-catch：")
do
    local ok, msg = xpcall(function()
        error("error via pcall catch")
    end, function()
        print(debug.traceback())
        return "error via msg handle"
    end)
    print(ok, msg)
end

